#!/bin/bash

agent_ip=$(ifconfig eth1 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')

auth_hash=$(curl -i -X POST -H 'Content-Type: application/json-rpc' -d '{"jsonrpc": "2.0", "method": "user.login", "params": { "user": "Admin", "password": "zabbix"}, "id": 1}' http://192.168.56.101/api_jsonrpc.php | sed -n 's/.*result":"\(.*\)",.*/\1/p')

curl -i -X POST -H 'Content-Type: application/json-rpc' -d "{\"jsonrpc\":\"2.0\",\"method\":\"host.create\",\"params\":{\"host\":\"Zabbix agent 2\",\"interfaces\":[{\"type\":1,\"main\":1,\"ip\":\"$agent_ip\",\"dns\":\"\",\"port\":10050,\"useip\":1}],\"groups\":[{\"groupid\":8}],\"templates\":[{\"templateid\":10001}]},\"auth\":\"$auth_hash\",\"id\":1}" http://192.168.56.101/api_jsonrpc.php
